### ISSUE TITLE
JCenter is being sunsetted

### ISSUE THREAD

**Issue by mradzinski** [isaac-udy/Enro#16]
Consider migrating to another package repository.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by isaac-udy** [comment]
Thanks - I am already looking into this. I will leave this issue open to put some updates into.

**Comment by isaac-udy** [comment]
I've now got a repository created on oss.sonatype, so will be syncing to maven central once I publish the first enro component to that repository. I'm about to go away for a few days, so it is unlikely this will happen before next week.

See link here: https://issues.sonatype.org/browse/OSSRH-65111?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by isaac-udy** [comment]
I have started getting publishing working with the sonatype repository. I will continue working on this over the weekend. My current plan is to release 1.3.0, and publish that version to maven central. The upgrade to 1.3.0 might be a little painful, as I am intending to migrate the package names to "dev.enro" instead of "nav.enro", as "enro.dev" is a domain that I control.

Other than the package name change, the other major change in 1.3.0 will be that "enro-result" will no longer exist, as I have decided that this functionality should be a core part of Enro, and 1.3.0 will pull everything from "enro-result" into "enro-core". `ResultNavigationKey` will also be renamed `NavigationKey.Result`. 

If you *really* need to keep using 1.2.x, these artifacts will remain available through Github packages.

Please let me know in advance if you see any major issues with this.

**Comment by isaac-udy** [comment]
I've published the first release of Enro 1.3.0 to the Sonatype OSS repository. I am currently awaiting the sync to Maven Central to be activated (you can check it out the progress on this here: https://issues.sonatype.org/browse/OSSRH-65111)

**Comment by isaac-udy** [comment]
It appears the sync to Maven Central has been activated. Enro 1.3.0 and higher will now be available on Maven Central, so I'm closing this issue. 

Please be aware that the correct dependency is now `dev.enro:enro:1.3.0`, **not** `nav.enro`. 

Let me know if you have any trouble. 

Thanks for raising the issue and showing interest in Enro!
