### ISSUE TITLE
Why is this minSdkVersion = 21 ? could it be at least 19 ?

### ISSUE THREAD

**Issue by thegarlynch** [isaac-udy/Enro#7]

**Comment by isaac-udy** [comment]
The minSdk is currently set to 21 mainly because that's the "default" minSdk I use for all my projects. I've just had a quick look, and it *should* be possible for me to drop the minSdk to 16 relatively easily.

I can't guarantee that it will work correctly in all situations, but I will look at adding that for the next release (some time later this week). 

I will update this issue after I've made this change. 

Thanks for your feature request!

**Comment by isaac-udy** [comment]
Hi! I've dropped the minimum SDK version to 16 in the latest version of Enro (1.2.2). Please check this out and provide any feedback. I'll be happy to look into any issues or feature requests you have. 

Thanks for supporting Enro!

**Comment by thegarlynch** [comment]
thank you, i will gladly refactor my navigation component to this now.
